server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.1.106
    username: leyou
    password: leyou
    virtual-host: /leyou
leyou:
  sms:
    accessKeyId: LTAI4FmubZzGGvLYaavgUbJf	  # 你自己的accessKeyId
    accessKeySecret: 02Tg4dmiW4Z3wZvOWyLzwjIpQLcarD # 你自己的AccessKeySecret
    signName: howe # 签名名称
    verifyCodeTemplate: SMS_185845621 # 模板名称